config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :musicas
  resources :usuarios do
    resources :playlists, only: [:new, :create, :show, :index]
  end


  get '/usuarios/:id', to: 'usuarios#show', as: 'usuario'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/musica.rb
class Musica < ApplicationRecord
  has_many :playlists
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :usuario
  has_many :musicas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musicas_controller.rb
class MusicasController < ApplicationController
  before_action :set_musica, only: %i[ show edit update destroy ]

  # GET /musicas or /musicas.json
  def index
    @musicas = Musica.all
  end

  # GET /musicas/1 or /musicas/1.json
  def show
  end

  # GET /musicas/new
  def new
    @musica = Musica.new
  end

  # GET /musicas/1/edit
  def edit
  end

  # POST /musicas or /musicas.json
  def create
    @musica = Musica.new(musica_params)

    respond_to do |format|
      if @musica.save
        format.html { redirect_to musica_url(@musica), notice: "Musica was successfully created." }
        format.json { render :show, status: :created, location: @musica }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /musicas/1 or /musicas/1.json
  def update
    respond_to do |format|
      if @musica.update(musica_params)
        format.html { redirect_to musica_url(@musica), notice: "Musica was successfully updated." }
        format.json { render :show, status: :ok, location: @musica }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @musica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musicas/1 or /musicas/1.json
  def destroy
    @musica.destroy

    respond_to do |format|
      format.html { redirect_to musicas_url, notice: "Musica was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_musica
      @musica = Musica.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def musica_params
      params.require(:musica).permit(:nome, :artista, :album, :duracao, :spotify_id)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  # GET /playlists or /playlists.json
  def index
    @usuario = Usuario.find(params[:usuario_id])
    @playlists = @usuario.playlists
  end


  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @usuario = Usuario.find(params[:usuario_id])
    @playlist = @usuario.playlists.build
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @usuario = Usuario.find(params[:usuario_id])
    @playlist = @usuario.playlists.build(playlist_params)

    if @playlist.save
      redirect_to @usuario, notice: "Playlist criada com sucesso!"
    else
      render :new
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def playlist_params
    params.require(:playlist).permit(:nome, :descricao, :usuario_id)
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])
    @playlists = @usuario.playlists
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :senha, :data_de_nascimento, :genero, :spotify_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musicas_helper.rb
module MusicasHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoEstagio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musicas/_form.html.erb
<%= form_with(model: musica) do |form| %>
  <% if musica.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(musica.errors.count, "error") %> prohibited this musica from being saved:</h2>

      <ul>
        <% musica.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :artista, style: "display: block" %>
    <%= form.text_field :artista %>
  </div>

  <div>
    <%= form.label :album, style: "display: block" %>
    <%= form.text_field :album %>
  </div>

  <div>
    <%= form.label :duracao, style: "display: block" %>
    <%= form.number_field :duracao %>
  </div>

  <div>
    <%= form.label :spotify_id, style: "display: block" %>
    <%= form.text_field :spotify_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/musicas/_musica.html.erb
<div id="<%= dom_id musica %>">
  <p>
    <strong>Nome:</strong>
    <%= musica.nome %>
  </p>

  <p>
    <strong>Artista:</strong>
    <%= musica.artista %>
  </p>

  <p>
    <strong>Album:</strong>
    <%= musica.album %>
  </p>

  <p>
    <strong>Duracao:</strong>
    <%= musica.duracao %>
  </p>

  <p>
    <strong>Spotify:</strong>
    <%= musica.spotify_id %>
  </p>

</div>

app/views/musicas/edit.html.erb
<h1>Editing musica</h1>

<%= render "form", musica: @musica %>

<br>

<div>
  <%= link_to "Show this musica", @musica %> |
  <%= link_to "Back to musicas", musicas_path %>
</div>

app/views/musicas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Musicas</h1>

<div id="musicas">
  <% @musicas.each do |musica| %>
    <%= render musica %>
    <p>
      <%= link_to "Show this musica", musica %>
    </p>
  <% end %>
</div>

<%= link_to "New musica", new_musica_path %>

app/views/musicas/new.html.erb
<h1>New musica</h1>

<%= render "form", musica: @musica %>

<br>

<div>
  <%= link_to "Back to musicas", musicas_path %>
</div>

app/views/musicas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @musica %>

<div>
  <%= link_to "Edit this musica", edit_musica_path(@musica) %> |
  <%= link_to "Back to musicas", musicas_path %>

  <%= button_to "Destroy this musica", @musica, method: :delete %>
</div>

app/views/playlists/_form.html.erb
<h1>Nova Playlist</h1>

<%= form_with(model: [@usuario, @playlist], url: usuario_playlists_path(@usuario)) do |form| %>
  <%= form.label :nome %>
  <%= form.text_field :nome %>

  <%= form.label :descricao %>
  <%= form.text_area :descricao %>

  <%= form.submit "Criar Playlist" %>
<% end %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p>
    <strong>Nome:</strong>
    <%= playlist.nome %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= playlist.descricao %>
  </p>

</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<h1>Playlists de <%= @usuario.nome %></h1>

<% @playlists.each do |playlist| %>
  <h2><%= link_to playlist.nome, usuario_playlist_path(@usuario, playlist) %></h2>
  <p><%= playlist.descricao %></p>
<% end %>
    

app/views/playlists/new.html.erb
<%= render "form", playlist: @playlist %>

<br>

app/views/playlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playlist %>

<div>
  <%= link_to "Edit this playlist", edit_playlist_path(@playlist) %> |
  <%= link_to "Back to playlists", playlists_path %>

  <%= button_to "Destroy this playlist", @playlist, method: :delete %>
</div>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :senha, style: "display: block" %>
    <%= form.text_field :senha %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>

  <div>
    <%= form.label :genero, style: "display: block" %>
    <%= form.text_field :genero %>
  </div>

  <div>
    <%= form.label :spotify_token, style: "display: block" %>
    <%= form.text_field :spotify_token %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nome:</strong>
    <%= usuario.nome %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= usuario.email %>
  </p>

  <p>
    <strong>Senha:</strong>
    <%= usuario.senha %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= usuario.data_de_nascimento %>
  </p>

  <p>
    <strong>Genero:</strong>
    <%= usuario.genero %>
  </p>

  <p>
    <strong>Spotify token:</strong>
    <%= usuario.spotify_token %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Show this usuario", @usuario %> |
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Usuarios</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Show this usuario", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "New usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Back to usuarios", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<!-- app/views/usuarios/show.html.erb -->
<h1><%= @usuario.nome %></h1>

<p><strong>Email:</strong> <%= @usuario.email %></p>
<p><strong>Data de nascimento:</strong> <%= @usuario.data_de_nascimento %></p>
<p><strong>Gênero:</strong> <%= @usuario.genero %></p>

<h2>Nome das Playlists:</h2>
<ul>
  <% @playlists.each do |playlist| %>
    <li><%= playlist.nome %></li>
  <% end %>
</ul>


<div>
  <%= link_to "Edit this usuario", edit_usuario_path(@usuario) %> |
  <%= link_to "Back to usuarios", usuarios_path %>

  <div class="actions">
    <%= link_to "Criar nova playlist", new_usuario_playlist_path(@usuario), class: "button is-primary" %>
  </div>

  <%= button_to "Destroy this usuario", @usuario, method: :delete %>
</div>